gui:
  spinner:
    frames:
      - ":<"
      - ":c"
      - ":("
      - ":I"
      - ":)"
      - ":>"
      - ":D"
      - ":O"
    rate: 80
  nerdFontsVersion: "3"
  showFileIcons: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
